os: linux
dist: trusty
language: python
services: docker

env:
  global:
    - BASE=compdatasci/vscode-desktop:latest

before_script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker pull $BASE

script:
  - docker build --tag chiao/vn-x11vnc-desktop:latest .
  - docker push $DOCKER_USERNAME/vn-x11vnc-desktop
